### ISSUE TITLE
@references with @import doesn't appear to work

### ISSUE THREAD

**Issue by asos-tomp** [dehuszar/postcss-reference#5]
Firstly, thanks for (what seems to be) a solution to a problem that's seemingly imperfectly solved elsewhere.

However, my use-case predicates styles held on disk in a separate css file, which I'd like to import and then reference.

The given example:
```css
/* Input */
@reference {
    @import 'pure.css';
}

button {
    @references .pure-button, .pure-button-primary;
}
```
...doesn't seem to work, having copied [pure.css](https://cdn.jsdelivr.net/npm/purecss@3.0.0/build/pure-min.css) (named `pure.css` in the local folder) - the output is always:
```css
button {}
```

I notice that there are tests for this behaviour - and, in-fact, running the following:
```js
(await require("postcss")([require("./index.js")]).process(require("fs").readFileSync("./test/at-import-support.css"), { from: "./test/at-import-support.css" })).css
```
...from the repo appears to work fine:
```css
header {
    color: blue;
    padding: 0;
    box-sizing: border-box;
    width: 100%;
    display: block;
    margin: 1em;
}
```
However, if this is installed as an NPM package in `node_modules`, and the same `test/` folder structure is created in a consumer, when attempting:
```js
(await require("postcss")([require("postcss-reference")]).process(require("fs").readFileSync("./test/at-import-support.css"), { from: "./test/at-import-support.css" })).css
```
...produces:
```css
header {
   display: block;
   margin: 1em;
}
```
...i.e. the imported rules appear not to have been found.   

if `npm link` / `yarn link` is used to bring `postcss-reference` in instead, everything seems to work.  So I assume something up with the directory structure when installed as a node module.

I will investigate and hopefully provide a fix!  But thought I'd let you know what I'd found, in-case it's something you'd noticed before and I'm just doing something stupid.

**Comment by asos-tomp** [comment]
Hmm... I appear to have an invalid npm package - the `CHANGELOG.md` I have is for `v2.0.0` yet the package.json talks of `2.1.0`

Apologies if this is the ultimate cause - will try and purge the upstream package clone.

**Comment by dehuszar** [comment]
Hey there @asos-tomp .  My apologies for letting this sit.  I somehow missed that there were open issues.  I'll have to review my notifications settings to see what happened there.  Either way, it looks like you were correct, I had not pushed up the version change code to github, though the release had made its way to npm.

If you're still interested in trying out the library, give it a whirl.  It works on my machine.  :sweat_smile:

**Comment by asos-tomp** [comment]
Thanks for getting back to me!

I think the latest (`2.1.0`) version on NPM is either immutable or not been updated, since [it still shows](https://www.npmjs.com/package/postcss-reference/v/2.1.0?activeTab=code) for `/lib/find-referenceable-rules.js`:
```js
module.exports = (atRule, target) => {
  atRule.walkRules(function(rule) {
    target.push(rule);
  });
  
  atRule.remove();
};
```
...rather than what's in github:
```js
const fs = require('fs');
const postcss = require('postcss');

const constructPath = (expression, importTarget) => {
  const scrubbedTarget = importTarget.replaceAll('"', '');
  switch(true) {
    case scrubbedTarget.startsWith('../'):
      const targetArray = scrubbedTarget.split('../')
      const numParentFolders = targetArray.slice(0, -1).length;
      const target = targetArray.slice(-1);
      const rootPath = expression.split('/').slice(0, -numParentFolders).join('/')
      
      return `${rootPath}/${target}`;
    default:
      return `${expression}${scrubbedTarget.replace('./', '/')}`
  }
}


module.exports = (atRule, target) => {
  const pushRulesToTarget = (rule) => {
    target.push(rule);
  }

  atRule.walkAtRules(function(atRule) {
    if (atRule.name === "import") {
      const originatingImportSourcePath = atRule.source.input.file.split('/').slice(0, -1).join('/');

      const path = constructPath(originatingImportSourcePath, atRule.params);

      if (path.startsWith('http')) {
        console.log('Retrieval of remote CSS files via URL is coming soon, but not ready yet.')
      } else {
        const importedRules = fs.readFileSync(path, 'utf-8');

        const root = postcss.parse(importedRules);

        root.walkRules(pushRulesToTarget);
      }
    }
  })

  atRule.walkRules(pushRulesToTarget);
  
  atRule.remove();
};
```

**Comment by dehuszar** [comment]
@asos-tomp Thanks for bearing with me.  As a non-regular open-source developer, I'm still building my package release muscles here.  2.2.1 should now be released (I found a bug while triple checking the original fix).  Can you try to install that and see if that fixes things on your end?

**Comment by TomStrepsil** [comment]
Nice one!  Much appreciated.  [2.2.1](https://www.npmjs.com/package/postcss-reference/v/2.2.1?activeTab=code) looks good.

**Comment by dehuszar** [comment]
Closing this out then.  Thanks for bringing the issue to my attention.
